version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: raizen_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  raizen:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    container_name: raizen_container
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
